apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lofi-charts.fullname" . }}
  labels:
    {{- include "lofi-charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lofi-charts.customLabels" . | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.otherName }}
      labels:
        {{- include "lofi-charts.customLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: {{ .Values.env.name }}
              value: {{ .Values.env.value }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
