apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- include "genre-charts.deploymentLabels" . | nindent 2 }}
  labels:
    {{- include "genre-charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "genre-charts.customLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ .Values.app.name}}
      labels:
        {{- include "genre-charts.customLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.containername }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: {{ .Values.environment.name }}
              value: {{ .Values.environment.value }}
