apiVersion: v1
kind: Service
metadata:
  {{- include "genre-charts.serviceName" . | nindent 2 }}
  labels:
    {{- include "genre-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "genre-charts.customLabels" . | nindent 4 }}
