apiVersion: v1
kind: Service
metadata:
  name: {{ include "genre-charts.serviceName" . | nindent 2 }}
  labels:
    {{- include "genre-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "genre-charts.selectorLabels" . | nindent 4 }}
